"""Emit the malloy-publisher dynamic study report from ablation traces.

Usage: python scripts/malloy_dynamic_report.py > reports/malloy-publisher/dynamic_report.md

Every number in the output is parsed from the trace JSONL files; nothing is
hand-typed. Selects the newest run dir per ablation contract.
"""
import glob
import json
import os
import re

RUN_ROOT = "runs/malloy-publisher"
GOALS = ["count", "breakdown", "model"]


def latest_dir(goal):
    dirs = sorted(glob.glob(f"{RUN_ROOT}/*/malloy_abl_{goal}"), key=os.path.getmtime)
    return dirs[-1] if dirs else None


def parse(fp):
    tok = turns = qerr = 0
    end, ans = "", ""
    for line in open(fp):
        e = json.loads(line)
        ev = e["event"]
        if ev == "model_response":
            turns += 1
            u = e.get("usage") or {}
            tok += u.get("total_tokens", 0) or 0
        elif ev == "tool_result" and e.get("name") == "malloy_executeQuery" \
                and '"error"' in e["result"][:40]:
            qerr += 1
        elif ev == "final_answer":
            ans = e["content"]
        elif ev == "run_end":
            end = e["outcome"]
    return turns, tok, qerr, end, ans


def main():
    print("<!-- Generated by scripts/malloy_dynamic_report.py from trace JSONL. -->\n")
    print("# Dynamic study: malloy-publisher MCP surface × agent skill delivery\n")
    print("- **Target:** `ms2data/malloy-publisher:latest` (official image), "
          "DuckDB sample config, MCP on :4040")
    print("- **Skill bodies injected from:** `malloydata/publisher@ad6c09b` "
          "(repo files; the released image serves 4 utility prompts, not the "
          "28 skills present on main)")
    print("- **Contracts:** `contracts/malloy_abl_{count,breakdown,model}.yaml` "
          "— 3 goals × 3 models × {baseline, skills_injected}, n=1")
    print("- **Query-goal injection:** malloy-queries + gotchas-queries; "
          "model goal: malloy-modeling\n")

    print("| goal | model | cell | outcome | turns | tokens | executeQuery errors |")
    print("|---|---|---|---|---|---|---|")
    answers = []
    for goal in GOALS:
        d = latest_dir(goal)
        for fp in sorted(glob.glob(f"{d}/trace_*.jsonl")):
            m = re.search(r"trace_(.+)_(baseline|skills_injected)_r1", fp)
            model, cell = m.groups()
            turns, tok, qerr, end, ans = parse(fp)
            print(f"| {goal} | {model} | {cell} | {end} | {turns} | {tok:,} | {qerr} |")
            if goal == "count" and ans:
                answers.append((model, cell, " ".join(ans.split())[:110]))

    print("\n## Final answers, count goal (ground truth: 344,827 — "
          "verified via malloy_executeQuery)\n")
    for model, cell, ans in answers:
        print(f"- **{model} / {cell}:** {ans}")

    print("""
## Run directories

""")
    for goal in GOALS:
        print(f"- `{latest_dir(goal)}`")

    print("""
## Disclosure: adapter defect during the earlier probe phase

The first probe runs (dirs `20260714_1345*`–`20260714_1347*`) contained a
harness defect: the MCP adapter masked embedded-resource tool results as
`[resource content]`, and models answered from the placeholder. Those runs
are retained for the record but superseded; the ablation runs above are
post-fix. Grep `"resource content"` in the run root to see the affected
traces.

## Reproduction

```bash
docker run -d -p 4000:4000 -p 4040:4040 \\
  -v $PWD/publisher.config.json:/publisher/publisher.config.json:ro \\
  ms2data/malloy-publisher:latest   # config: publisher.config.example.duckdb.json
python -m harnessbench.cli run contracts/malloy_abl_count.yaml \\
  --target mcp:http:http://localhost:4040/mcp --no-grade
python scripts/malloy_dynamic_report.py
```
""")


if __name__ == "__main__":
    main()
